variables:
    BUILD_CONCURRENCY: "10"
    GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - package

.cache-paths-spec: &cache-paths
    - build

.linux-cache-spec-template: &linux-cache-spec
    cache:
        key: ${CI_COMMIT_REF_SLUG}-${CI_JOB_NAME}
        paths: *cache-paths

.windows-cache-spec-template: &windows-cache-spec
    cache:
        paths: *cache-paths
        key: "%CI_COMMIT_REF_SLUG%-%CI_JOB_NAME%-%CI_RUNNER_ID%"

.artifacts-spec-build-linux-template: &artifact-spec-build-linux
    artifacts:
        name: "mce_${CI_COMMIT_REF_SLUG}_${CI_JOB_ID}_${CI_COMMIT_SHA}_${CI_JOB_NAME}"
        expire_in: 1 day
        paths:
        - ${BUILD_COMPILER_NAME}

.artifacts-spec-build-windows-template: &artifact-spec-build-windows
    artifacts:
        name: "mce_%CI_COMMIT_REF_SLUG%_%CI_JOB_ID%_%CI_COMMIT_SHA%_%CI_JOB_NAME%"
        expire_in: 1 day
        paths:
        - "%BUILD_COMPILER_NAME%"

.linux-build-template: &linux-build-task
    stage: build
    <<: *linux-cache-spec    
    script:
    - cmake -E make_directory build
    - cd build
    - cmake -U*_DIR -G "Unix Makefiles" -DCMAKE_C_COMPILER=${BUILD_C_COMPILER} -DCMAKE_CXX_COMPILER=${BUILD_CXX_COMPILER} -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DSANITIZER_INSTRUMENTATION=${BUILD_SANITIZE} -DCMAKE_INSTALL_PREFIX=${BUILD_COMPILER_NAME} ..
    - cmake --build . --target mce_demo -- -j ${BUILD_CONCURRENCY}
    - cmake --build . --target install-mce-demo -- -j ${BUILD_CONCURRENCY}
    - sha1sum -b multicore_engine_demo_assets/*.lu* multicore_engine_demo_assets/models/*.model
    - cd ..
    - cmake -E rename build/${BUILD_COMPILER_NAME} ${BUILD_COMPILER_NAME}
    - glslangValidator -v

.mingw-build-template: &mingw-build-task
    stage: build
    <<: *windows-cache-spec    
    script:
    - cmake -E make_directory build
    - cd build
    - cmake -U*_DIR -G "MinGW Makefiles" -DCMAKE_C_COMPILER=%BUILD_C_COMPILER% -DCMAKE_CXX_COMPILER=%BUILD_CXX_COMPILER% -DCMAKE_BUILD_TYPE=%BUILD_TYPE% -DCMAKE_INSTALL_PREFIX=%BUILD_COMPILER_NAME% ..
    - cmake --build . --target mce_demo -- -j %BUILD_CONCURRENCY%
    - cmake --build . --target install-mce-demo -- -j %BUILD_CONCURRENCY%
    - cd ..
    - cmake -E rename build/%BUILD_COMPILER_NAME% %BUILD_COMPILER_NAME%
    - glslangValidator -v

.msbuild-build-template: &msbuild-build-task
    stage: build
    <<: *windows-cache-spec    
    script:
    - cmake -E make_directory build
    - cd build
    - cmake -U*_DIR -DCMAKE_INSTALL_PREFIX=%BUILD_COMPILER_NAME% -G "Visual Studio 15 2017 Win64" ..
    - cmake --build . --config %BUILD_TYPE% --target mce_demo -- /m:%BUILD_CONCURRENCY%
    - cmake --build . --config %BUILD_TYPE% --target install-mce-demo -- /m:%BUILD_CONCURRENCY%
    - cd ..
    - cmake -E rename build/%BUILD_COMPILER_NAME% %BUILD_COMPILER_NAME%
    - glslangValidator -v

.package-task-template: &package-task
    stage: package
    variables:
        GIT_STRATEGY: none
    script:
    - sha1sum -b gcc/assets/* clang/assets/* > checksums.txt
    - cat checksums.txt | sort
    - mv gcc/assets/ assets/
    - mv gcc/default.cfg default.cfg
    - mv gcc/bin gcc-bin
    - mv clang/bin clang-bin
    - rm -r clang/assets/ clang/default.cfg
    - rmdir gcc clang
    image: alpine:latest
    artifacts: &package-artifact-spec
        name: "mce_${CI_COMMIT_REF_SLUG}_${CI_JOB_ID}_${CI_COMMIT_SHA}"
        paths:
        - assets
        - gcc-bin
        - clang-bin
        - checksums.txt
        - licenses

gcc-release-build:
    variables:
        BUILD_CXX_COMPILER: "g++"
        BUILD_C_COMPILER: "gcc"
        BUILD_TYPE: "Release"
        BUILD_COMPILER_NAME: "gcc"
        BUILD_SANITIZE: "NO"
    image: $CI_REGISTRY/ci-util/cpp/gcc/release
    <<: *linux-build-task
    <<: *artifact-spec-build-linux

clang-release-build:
    variables:
        BUILD_CXX_COMPILER: "clang++"
        BUILD_C_COMPILER: "clang"
        BUILD_TYPE: "Release"
        BUILD_COMPILER_NAME: "clang"
        BUILD_SANITIZE: "NO"
    image: $CI_REGISTRY/ci-util/cpp/clang/release
    <<: *linux-build-task
    <<: *artifact-spec-build-linux
    
scan-build:
    dependencies: []
    stage: build
    script:
    - mkdir -p build && cd build
    - cmake -U*_DIR -G "Unix Makefiles" -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Debug -DSTATIC_ANALYSIS_ONLY=YES ..
    - scan-build --status-bugs make -j $[$(grep -c ^processor /proc/cpuinfo)+2] config=debug CC=clang CXX=clang++ mce_demo
    image: $CI_REGISTRY/ci-util/cpp/clang/release
    <<: *linux-cache-spec
        
license-pack-linux:
    dependencies: []
    stage: build
    script:
    - multicore_engine/create_license_pack_linux.sh
    - cp "multicore_engine_demo_assets/textures_src/About these PBR files.txt" licenses\linux\pbr_materials.txt
    image: $CI_REGISTRY/ci-util/cpp/clang/release
    artifacts:
        name: "mce_${CI_COMMIT_REF_SLUG}_${CI_JOB_ID}_${CI_COMMIT_SHA}_${CI_JOB_NAME}"
        expire_in: 1 day
        paths:
        - licenses

package-base:
    <<: *package-task
    except: 
    - tags
    artifacts:
        <<: *package-artifact-spec
        expire_in: 2 weeks

package-tags:
    <<: *package-task
    only: 
    - tags

